Document: libavp
Title: Debian libavp Manual
Author: <insert document author here>
Abstract: This manual describes what libavp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libavp/libavp.sgml.gz

Format: postscript
Files: /usr/share/doc/libavp/libavp.ps.gz

Format: text
Files: /usr/share/doc/libavp/libavp.text.gz

Format: HTML
Index: /usr/share/doc/libavp/html/index.html
Files: /usr/share/doc/libavp/html/*.html
